export const translations = {
  es: {
    nav: { tareas: 'Tareas', gestionar: 'Gestionar', resumen: 'Resumen', analizar: 'Analizar', ajustes: 'Ajustes', logout: 'Cerrar Sesión' },
    common: { loading: 'Cargando...', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', create: 'Crear', name: 'Nombre', time: 'Hora', confirm_delete: '¿Estás seguro de que deseas eliminar este hábito? Esta acción no se puede deshacer.', days: 'Días' },
    auth: { title: 'GoHabits', login: 'Iniciar Sesión', signup: 'Registrarse', welcome_back: 'Bienvenido de nuevo. Sigue mejorando hoy.', welcome_new: 'Comienza a monitorizar tus hábitos de forma simple.', email: 'Correo Electrónico', password: 'Contraseña', demo: 'Probar en Modo Demo (Local)', has_account: '¿Ya tienes una cuenta? Inicia sesión', no_account: '¿No tienes cuenta? Registrate gratis' },
    tareas: { subtitle: 'Seguimiento Diario', no_habits: 'No tienes hábitos programados para hoy.', habits_scheduled: 'Hoy tienes {count} hábitos programados.', progress: 'Progreso', completed: 'Completado', justified: 'Justificado', pending: 'Pendiente', reset: 'Reiniciar', new_quick: 'Nuevo Rápido', placeholder: 'Ej. Meditar 10 minutos...', add: 'Añadir', justify_title: 'Justificar Inasistencia', justify_desc: '¿Por qué no puedes realizar este hábito hoy? Añade una nota breve.', justify_placeholder: 'Ej. Me siento cansado, viaje de trabajo...', save_reason: 'Guardar Motivo' },
    gestionar: { title: 'Gestionar Hábitos', subtitle: 'Crea, edita o elimina tus hábitos y define sus horarios sugeridos.', new_habit: 'Nuevo Hábito', edit_habit: 'Editar Hábito', name_placeholder: 'Ej. Meditación, Gimnasio, Leer...', schedule: 'Programación de Días', all_week: 'Toda la semana', mon_to_fri: 'Lunes a Viernes', custom: 'Personalizado', time_suggested: 'Hora sugerida', save_changes: 'Guardar Cambios' },
    resumen: { title: 'Resumen del Día', subtitle: 'Visualiza tu progreso y despliega hábitos para ver tu constancia anual.', progress_general: 'Progreso General de Hoy', legend_completed: 'Completado', legend_justified: 'Justificado', legend_pending: 'Pendiente', legend_rest: 'Descanso', legend_missed: 'No hecho', history_title: 'Registro Histórico Anual', tooltip_info: 'Pasa el cursor o pulsa sobre un día amarillo para ver el motivo.', frequency: 'Frecuencia' },
    analizar: { title: 'Analizar Hábitos', subtitle: 'Monitorea tus rachas y constancia general de un vistazo.', current_streak: 'Racha Actual', max_streak: 'Racha Máxima', consistency: 'Constancia', commitment: 'Días de compromiso histórico', times: 'veces', days_count: 'días', creation: 'Fecha de creación', select: 'Selecciona un Hábito', comparison: 'Comparativa de Constancia (%)' },
    ajustes: { title: 'Ajustes', subtitle: 'Configura tu idioma, perfiles de rutinas y sesión.', language: 'Idioma de la aplicación', profiles: 'Perfiles de Rutinas', active_profile: 'Perfil activo', new_profile: 'Nuevo Perfil', create_profile: 'Crear Perfil', cannot_delete_main: 'El perfil Principal no se puede eliminar.', profiles_desc: 'Crea diferentes perfiles para separar tus rutinas (ej. Gimnasio, Vacaciones). Cada perfil tiene sus propias tareas independientes.', demo_alert: 'Ejecutando en Modo Demo (Local)', logout: 'Cerrar Sesión' },
    importar: { title: 'Importar Rutinas', subtitle: 'Agrega rutinas populares o creadas por la comunidad.', default_routines: 'Rutinas Predeterminadas', community_routines: 'Rutinas de la Comunidad', share_routine: 'Compartir Rutina con la Comunidad', share_desc: 'Comparte tu lista de hábitos de este perfil para que otros puedan utilizarlos como plantilla.', share_btn: 'Publicar Rutina del Perfil', import_btn: 'Importar', import_modal_title: 'Importar Rutina', import_modal_desc: 'Elige si deseas importar los hábitos de esta rutina en tu perfil activo o crear uno nuevo.', target_profile: 'Perfil de destino', current_profile: 'Perfil actual ({name})', new_profile_option: 'Crear nuevo perfil', new_profile_name: 'Nombre del nuevo perfil', share_success: '¡Rutina compartida con éxito!', import_success: '¡Rutina importada con éxito!' }
  },
  en: {
    nav: { tareas: 'Tasks', gestionar: 'Manage', resumen: 'Summary', analizar: 'Analyze', ajustes: 'Settings', logout: 'Log Out' },
    common: { loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', create: 'Create', name: 'Name', time: 'Time', confirm_delete: 'Are you sure you want to delete this habit? This action cannot be undone.', days: 'Days' },
    auth: { title: 'GoHabits', login: 'Log In', signup: 'Sign Up', welcome_back: 'Welcome back. Keep improving today.', welcome_new: 'Start tracking your habits the simple way.', email: 'Email Address', password: 'Password', demo: 'Try Demo Mode (Local)', has_account: 'Already have an account? Log In', no_account: "Don't have an account? Sign Up Free" },
    tareas: { subtitle: 'Daily Tracking', no_habits: 'No habits scheduled for today.', habits_scheduled: 'You have {count} habits scheduled for today.', progress: 'Progress', completed: 'Completed', justified: 'Justified', pending: 'Pending', reset: 'Reset', new_quick: 'Quick Add', placeholder: 'e.g., Meditate 10 min...', add: 'Add', justify_title: 'Justify Absence', justify_desc: 'Why can you not complete this habit today? Add a short note.', justify_placeholder: 'e.g., Feeling tired, business trip...', save_reason: 'Save Reason' },
    gestionar: { title: 'Manage Habits', subtitle: 'Create, edit, or delete your habits and define suggested times.', new_habit: 'New Habit', edit_habit: 'Edit Habit', name_placeholder: 'e.g., Meditation, Gym, Reading...', schedule: 'Days Configuration', all_week: 'All Week', mon_to_fri: 'Monday to Friday', custom: 'Custom', time_suggested: 'Suggested time', save_changes: 'Save Changes' },
    resumen: { title: "Today's Summary", subtitle: 'Visualize your progress and expand habits to see your annual consistency.', progress_general: "Today's General Progress", legend_completed: 'Completed', legend_justified: 'Justified', legend_pending: 'Pending', legend_rest: 'Rest', legend_missed: 'Missed', history_title: 'Annual Calendar Grid', tooltip_info: 'Hover or tap a yellow day to see the justification reason.', frequency: 'Frequency' },
    analizar: { title: 'Analyze Habits', subtitle: 'Monitor your streaks and overall consistency at a glance.', current_streak: 'Current Streak', max_streak: 'Max Streak', consistency: 'Consistency', commitment: 'Historical commitment days', times: 'times', days_count: 'days', creation: 'Creation date', select: 'Select a Habit', comparison: 'Consistency Comparison (%)' },
    ajustes: { title: 'Settings', subtitle: 'Configure your language, routine profiles, and session.', language: 'App Language', profiles: 'Routine Profiles', active_profile: 'Active Profile', new_profile: 'New Profile', create_profile: 'Create Profile', cannot_delete_main: 'The Main profile cannot be deleted.', profiles_desc: 'Create different profiles to separate your routines (e.g., Gym, Vacation). Each profile has its own independent tasks.', demo_alert: 'Running in Demo Mode (Local)', logout: 'Log Out' },
    importar: { title: 'Import Routines', subtitle: 'Add popular routines or ones created by the community.', default_routines: 'Default Routines', community_routines: 'Community Routines', share_routine: 'Share Routine with Community', share_desc: 'Share your list of habits from this profile so others can use it as a template.', share_btn: 'Publish Profile Routine', import_btn: 'Import', import_modal_title: 'Import Routine', import_modal_desc: 'Choose whether to import this routine into your active profile or create a new one.', target_profile: 'Target Profile', current_profile: 'Current profile ({name})', new_profile_option: 'Create new profile', new_profile_name: 'New profile name', share_success: 'Routine shared successfully!', import_success: 'Routine imported successfully!' }
  },
  fr: {
    nav: { tareas: 'Tâches', gestionar: 'Gérer', resumen: 'Résumé', analizar: 'Analyser', ajustes: 'Paramètres', logout: 'Déconnexion' },
    common: { loading: 'Chargement...', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', create: 'Créer', name: 'Nom', time: 'Heure', confirm_delete: 'Êtes-vous sûr de vouloir supprimer cette habitude ? Cette action est irréversible.', days: 'Jours' },
    auth: { title: 'GoHabits', login: 'Connexion', signup: 'S\'inscrire', welcome_back: 'Bon retour. Continuez à vous améliorer aujourd\'hui.', welcome_new: 'Commencez à suivre vos habitudes en toute simplicité.', email: 'Adresse e-mail', password: 'Mot de passe', demo: 'Mode Démo (Local)', has_account: 'Déjà un compte ? Connexion', no_account: 'Pas de compte ? Inscrivez-vous gratuitement' },
    tareas: { subtitle: 'Suivi Quotidien', no_habits: 'Aucune habitude programmée pour aujourd\'hui.', habits_scheduled: 'Vous avez {count} habitudes programmées aujourd\'hui.', progress: 'Progression', completed: 'Complété', justified: 'Justifié', pending: 'En attente', reset: 'Réinitialiser', new_quick: 'Ajout Rapide', placeholder: 'ex. Méditer 10 min...', add: 'Ajouter', justify_title: 'Justifier l\'absence', justify_desc: 'Pourquoi ne pouvez-vous pas faire cette habitude aujourd\'hui ? Ajoutez une note.', justify_placeholder: 'ex. Fatigué, voyage d\'affaires...', save_reason: 'Sauvegarder le motif' },
    gestionar: { title: 'Gérer les Habitudes', subtitle: 'Créez, modifiez ou supprimez vos habitudes et définissez les heures suggérées.', new_habit: 'Nouvelle Habitude', edit_habit: 'Modifier l\'Habitude', name_placeholder: 'ex. Méditation, Musculation, Lecture...', schedule: 'Configuration des Jours', all_week: 'Toute la semaine', mon_to_fri: 'Lundi au Vendredi', custom: 'Personnalisé', time_suggested: 'Heure suggérée', save_changes: 'Sauvegarder les modifications' },
    resumen: { title: 'Résumé du Jour', subtitle: 'Visualisez votre progression et déployez vos habitudes pour voir votre constance annuelle.', progress_general: 'Progression Générale d\'Aujourd\'hui', legend_completed: 'Complété', legend_justified: 'Justifié', legend_pending: 'En attente', legend_rest: 'Repos', legend_missed: 'Manqué', history_title: 'Calendrier Annuel', tooltip_info: 'Passez le curseur ou appuyez sur un jour jaune pour voir la justification.', frequency: 'Fréquence' },
    analizar: { title: 'Analyser les Habitudes', subtitle: 'Suivez vos séries et votre constance globale en un coup d\'œil.', current_streak: 'Série Actuelle', max_streak: 'Série Maximale', consistency: 'Constance', commitment: 'Jours d\'engagement historique', times: 'fois', days_count: 'jours', creation: 'Date de création', select: 'Sélectionnez une Habitude', comparison: 'Comparatif de Constance (%)' },
    ajustes: { title: 'Paramètres', subtitle: 'Configurez la langue, les profils de routine y la session.', language: 'Langue de l\'application', profiles: 'Profils de Routine', active_profile: 'Profil actif', new_profile: 'Nouveau Profil', create_profile: 'Créer un Profil', cannot_delete_main: 'Le profil Principal ne peut pas être supprimé.', profiles_desc: 'Créez différents profils pour séparer vos routines (ex. Sport, Vacances). Chaque profil a ses propres tâches.', demo_alert: 'Mode Démo (Local) activé', logout: 'Déconnexion' },
    importar: { title: 'Importer des Routines', subtitle: 'Ajoutez des routines populaires ou de la communauté.', default_routines: 'Routines par Défaut', community_routines: 'Routines de la Communauté', share_routine: 'Partager la Routine', share_desc: 'Partagez vos habitudes de ce profil pour que d\'autres puissent les utiliser.', share_btn: 'Publier la Routine du Profil', import_btn: 'Importer', import_modal_title: 'Importer la Routine', import_modal_desc: 'Choisissez d\'importer cette routine dans votre profil actif ou d\'en créer un nouveau.', target_profile: 'Profil cible', current_profile: 'Profil actuel ({name})', new_profile_option: 'Créer un nouveau profil', new_profile_name: 'Nom du nouveau profil', share_success: 'Routine partagée avec succès !', import_success: 'Routine importée avec succès !' }
  },
  it: {
    nav: { tareas: 'Attività', gestionar: 'Gestisci', resumen: 'Riepilogo', analizar: 'Analizza', ajustes: 'Impostazioni', logout: 'Disconnetti' },
    common: { loading: 'Caricamento...', save: 'Salva', cancel: 'Annulla', delete: 'Elimina', edit: 'Modifica', create: 'Crea', name: 'Nome', time: 'Ora', confirm_delete: 'Sei sicuro di voler eliminare questa abitudine? L\'azione è irreversibile.', days: 'Giorni' },
    auth: { title: 'GoHabits', login: 'Accedi', signup: 'Registrati', welcome_back: 'Bentornato. Continua a migliorare oggi.', welcome_new: 'Inizia a tracciare le tue abitudini in modo semplice.', email: 'Indirizzo e-mail', password: 'Password', demo: 'Modalità Demo (Locale)', has_account: 'Hai già un account? Accedi', no_account: 'Non hai un account? Registrati gratis' },
    tareas: { subtitle: 'Tracciamento Giornaliero', no_habits: 'Nessuna abitudine programmata per oggi.', habits_scheduled: 'Oggi hai {count} abitudini programmate.', progress: 'Progresso', completed: 'Completato', justified: 'Giustificato', pending: 'In attesa', reset: 'Reimposta', new_quick: 'Aggiunta Rapida', placeholder: 'es. Meditare 10 min...', add: 'Aggiungi', justify_title: 'Giustifica Assenza', justify_desc: 'Perché non puoi completare l\'abitudine oggi? Aggiungi una nota.', justify_placeholder: 'es. Stanco, viaggio di lavoro...', save_reason: 'Salva Motivo' },
    gestionar: { title: 'Gestisci Abitudini', subtitle: 'Crea, modifica o elimina le tue abitudini e imposta gli orari suggeriti.', new_habit: 'Nuova Abitudine', edit_habit: 'Modifica Abitudine', name_placeholder: 'es. Meditazione, Palestra, Lettura...', schedule: 'Configurazione Giorni', all_week: 'Tutta la settimana', mon_to_fri: 'Lunedì al Venerdì', custom: 'Personalizzato', time_suggested: 'Ora suggerita', save_changes: 'Salva Modifiche' },
    resumen: { title: 'Riepilogo del Giorno', subtitle: 'Visualizza il progresso e vedi la costanza annuale delle tue abitudini.', progress_general: 'Progresso Generale di Oggi', legend_completed: 'Completato', legend_justified: 'Giustificato', legend_pending: 'In attesa', legend_rest: 'Riposo', legend_missed: 'Mancato', history_title: 'Calendario Annuale', tooltip_info: 'Passa il cursore o premi su un giorno giallo per vedere il motivo.', frequency: 'Frequenza' },
    analizar: { title: 'Analizza Abitudini', subtitle: 'Monitora la serie attuale, la massima e la costanza generale.', current_streak: 'Serie Attuale', max_streak: 'Serie Massima', consistency: 'Costanza', commitment: 'Giorni di impegno storico', times: 'volte', days_count: 'giorni', creation: 'Data di creazione', select: 'Seleziona un\'Abitudine', comparison: 'Confronto Costanza (%)' },
    ajustes: { title: 'Impostazioni', subtitle: 'Configura la lingua, i profili di routine e la sessione.', language: 'Lingua dell\'App', profiles: 'Profili Routine', active_profile: 'Profilo attivo', new_profile: 'Nuovo Profilo', create_profile: 'Crea Profilo', cannot_delete_main: 'Il profilo Principale non può essere eliminato.', profiles_desc: 'Crea profili diversi per separare le routine (es. Sport, Vacanze). Ogni profilo ha le sue attività.', demo_alert: 'Modalità Demo (Locale) attiva', logout: 'Disconnetti' },
    importar: { title: 'Importa Routine', subtitle: 'Aggiungi routine popolari o della comunità.', default_routines: 'Routine Predefinite', community_routines: 'Routine della Comunità', share_routine: 'Condividi Routine', share_desc: 'Condividi le abitudini di questo profilo come modello per gli altri.', share_btn: 'Pubblica Routine Profilo', import_btn: 'Importa', import_modal_title: 'Importa Routine', import_modal_desc: 'Scegli se importare questa routine nel tuo profilo attivo o crearne uno nuovo.', target_profile: 'Profilo di destinazione', current_profile: 'Profilo attuale ({name})', new_profile_option: 'Crea nuovo profilo', new_profile_name: 'Nome del nuovo profilo', share_success: 'Routine condivisa con successo!', import_success: 'Routine importata con successo!' }
  },
  ru: {
    nav: { tareas: 'Задачи', gestionar: 'Управление', resumen: 'Сводка', analizar: 'Анализ', ajustes: 'Настройки', logout: 'Выйти' },
    common: { loading: 'Загрузка...', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить', create: 'Создать', name: 'Название', time: 'Время', confirm_delete: 'Вы уверены, что хотите удалить эту привычку? Это действие необратимо.', days: 'Дни' },
    auth: { title: 'GoHabits', login: 'Войти', signup: 'Регистрация', welcome_back: 'С возвращением. Продолжайте совершенствоваться сегодня.', welcome_new: 'Начните отслеживать свои привычки простым способом.', email: 'Эл. почта', password: 'Пароль', demo: 'Демо-режим (Локально)', has_account: 'Уже есть аккаунт? Войти', no_account: 'Нет аккаунта? Зарегистрируйтесь бесплатно' },
    tareas: { subtitle: 'Ежедневный Трекинг', no_habits: 'На сегодня привычек не запланировано.', habits_scheduled: 'Сегодня запланировано привычек: {count}.', progress: 'Прогресс', completed: 'Выполнено', justified: 'Уважительная причина', pending: 'Ожидает', reset: 'Сбросить', new_quick: 'Быстро добавить', placeholder: 'Напр., Медитация 10 мин...', add: 'Добавить', justify_title: 'Указать причину пропуска', justify_desc: 'Почему вы не можете выполнить привычку сегодня? Добавьте заметку.', justify_placeholder: 'Напр., Устал, командировка...', save_reason: 'Сохранить причину' },
    gestionar: { title: 'Управление привычками', subtitle: 'Создавайте, редактируйте или удаляйте привычки и устанавливайте рекомендуемое время.', new_habit: 'Новая привычка', edit_habit: 'Редактировать привычку', name_placeholder: 'Напр., Медитация, Спортзал, Чтение...', schedule: 'Настройка дней', all_week: 'Вся неделя', mon_to_fri: 'С понедельника по пятницу', custom: 'Выбрать дни', time_suggested: 'Рекомендуемое время', save_changes: 'Сохранить изменения' },
    resumen: { title: 'Итоги дня', subtitle: 'Визуализируйте свой прогресс и просматривайте годовую статистику.', progress_general: 'Общий прогресс на сегодня', legend_completed: 'Выполнено', legend_justified: 'С причиной', legend_pending: 'Ожидает', legend_rest: 'Отдых', legend_missed: 'Пропущено', history_title: 'Годовой календарь активности', tooltip_info: 'Наведите курсор или нажмите на желтый день, чтобы увидеть причину.', frequency: 'Частота' },
    analizar: { title: 'Анализ привычек', subtitle: 'Следите за вашими сериями и общей стабильностью.', current_streak: 'Текущая серия', max_streak: 'Максимальная серия', consistency: 'Стабильность', commitment: 'Всего дней по расписанию', times: 'раз', days_count: 'дн.', creation: 'Дата создания', select: 'Выберите привычку', comparison: 'Сравнение стабильности (%)' },
    ajustes: { title: 'Настройки', subtitle: 'Настройте язык, профили и сессию.', language: 'Язык приложения', profiles: 'Профили привычек', active_profile: 'Активный профиль', new_profile: 'Новый профиль', create_profile: 'Создать профиль', cannot_delete_main: 'Основной профиль удалить нельзя.', profiles_desc: 'Создавайте профили для разделения привычек (напр., Спорт, Отпуск). В каждом профиле свои привычки.', demo_alert: 'Приложение запущено в демо-режиме', logout: 'Выйти' },
    importar: { title: 'Импорт рутин', subtitle: 'Добавляйте популярные шаблоны или рутины сообщества.', default_routines: 'Стандартные шаблоны', community_routines: 'Рутины сообщества', share_routine: 'Поделиться рутиной с сообществом', share_desc: 'Поделитесь списком привычек из этого профиля как шаблоном для других.', share_btn: 'Опубликовать рутину профиля', import_btn: 'Импортировать', import_modal_title: 'Импорт рутины', import_modal_desc: 'Выберите: импортировать в текущий профиль или создать новый.', target_profile: 'Профиль назначения', current_profile: 'Текущий профиль ({name})', new_profile_option: 'Создать новый профиль', new_profile_name: 'Имя нового профиля', share_success: 'Рутина успешно опубликована!', import_success: 'Рутина успешно импортирована!' }
  },
  zh: {
    nav: { tareas: '任务', gestionar: '管理', resumen: '概述', analizar: '分析', ajustes: '设置', logout: '退出登录' },
    common: { loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', edit: '编辑', create: '创建', name: '名称', time: '时间', confirm_delete: '您确定要删除此习惯吗？此操作无法撤销。', days: '天数' },
    auth: { title: 'GoHabits', login: '登录', signup: '注册', welcome_back: '欢迎回来。今天继续努力。', welcome_new: '开始轻松跟踪您的习惯。', email: '电子邮箱', password: '密码', demo: '体验演示模式（本地）', has_account: '已有账号？登录', no_account: '还没有账号？免费注册' },
    tareas: { subtitle: '每日跟踪', no_habits: '今天没有安排习惯。', habits_scheduled: '今天您有 {count} 个习惯安排。', progress: '进度', completed: '已完成', justified: '已请假', pending: '待处理', reset: '重置', new_quick: '快速添加', placeholder: '例如：冥想10分钟...', add: '添加', justify_title: '请假说明', justify_desc: '为什么今天无法完成此习惯？请添加简短说明。', justify_placeholder: '例如：感觉疲惫、出差...', save_reason: '保存原因' },
    gestionar: { title: '管理习惯', subtitle: '创建、编辑或删除您的习惯，并设定建议时间。', new_habit: '新习惯', edit_habit: '编辑习惯', name_placeholder: '例如：冥想、健身、阅读...', schedule: '日程配置', all_week: '整周', mon_to_fri: '周一至周五', custom: '自定义', time_suggested: '建议时间', save_changes: '保存修改' },
    resumen: { title: '今日概述', subtitle: '直观查看您的进度，并展开习惯以查看年度坚持率。', progress_general: '今日总进度', legend_completed: '已完成', legend_justified: '已请假', legend_pending: '待处理', legend_rest: '休息', legend_missed: '未做', history_title: '年度活动日历', tooltip_info: '将鼠标悬停或轻触黄色方块以查看请假原因。', frequency: '频率' },
    analizar: { title: '分析习惯', subtitle: '一目了然地监测您的连续天数和整体坚持率。', current_streak: '当前连续', max_streak: '最大连续', consistency: '坚持率', commitment: '历史应做天数', times: '次', days_count: '天', creation: '创建日期', select: '选择一个习惯', comparison: '坚持率对比 (%)' },
    ajustes: { title: '设置', subtitle: '配置您的语言、习惯配置文件和会话。', language: '应用语言', profiles: '习惯配置文件', active_profile: '当前配置文件', new_profile: '新配置文件', create_profile: '创建配置文件', cannot_delete_main: '无法删除主要配置文件。', profiles_desc: '创建不同的配置文件以区分您的日程（例如：健身、度假）。每个配置文件拥有独立的任务。', demo_alert: '正在以本地演示模式运行', logout: '退出登录' },
    importar: { title: '导入习惯', subtitle: '添加热门或社区创建的习惯模板。', default_routines: '预设习惯', community_routines: '社区习惯', share_routine: '分享习惯至社区', share_desc: '将此配置文件的习惯分享为模板供他人使用。', share_btn: '发布此配置文件的习惯', import_btn: '导入', import_modal_title: '导入习惯', import_modal_desc: '选择将此习惯导入到当前配置文件中还是创建一个新的。', target_profile: '目标配置文件', current_profile: '当前配置文件 ({name})', new_profile_option: '创建新配置文件', new_profile_name: '新配置文件名称', share_success: '习惯模板成功发布！', import_success: '习惯模板成功导入！' }
  },
  uk: {
    nav: { tareas: 'Завдання', gestionar: 'Керування', resumen: 'Звіт', analizar: 'Аналіз', ajustes: 'Налаштування', logout: 'Вийти' },
    common: { loading: 'Завантаження...', save: 'Зберегти', cancel: 'Скасувати', delete: 'Видалити', edit: 'Редагувати', create: 'Створити', name: 'Назва', time: 'Час', confirm_delete: 'Ви впевнені, що хочете видалити цю звичку? Цю дію не можна скасувати.', days: 'Дні' },
    auth: { title: 'GoHabits', login: 'Увійти', signup: 'Реєстрація', welcome_back: 'З поверненням. Продовжуйте вдосконалюватися сьогодні.', welcome_new: 'Почніть відстежувати свої звички простим способом.', email: 'Ел. пошта', password: 'Пароль', demo: 'Демо-режим (Локально)', has_account: 'Вже є акаунт? Увійти', no_account: 'Немає акаунта? Зареєструйтеся безкоштовно' },
    tareas: { subtitle: 'Щоденний Трекінг', no_habits: 'На сьогодні звичок не заплановано.', habits_scheduled: 'Сьогодні заплановано звичок: {count}.', progress: 'Прогрес', completed: 'Виконано', justified: 'З поважної причини', pending: 'Очікує', reset: 'Скинути', new_quick: 'Швидко додати', placeholder: 'Напр., Медіація 10 хв...', add: 'Додати', justify_title: 'Пояснити пропуск', justify_desc: 'Чому ви не можете виконати звичку сьогодні? Додайте замітку.', justify_placeholder: 'Напр., Втомився, відрядження...', save_reason: 'Зберегти причину' },
    gestionar: { title: 'Керування звичками', subtitle: 'Створюйте, редагуйте або видаляйте звички та встановлюйте рекомендований час.', new_habit: 'Нова звичка', edit_habit: 'Редагувати звичку', name_placeholder: 'Напр., Медіація, Спортзал, Читання...', schedule: 'Налаштування днів', all_week: 'Весь тижденень', mon_to_fri: 'З понеділка по п\'ятницю', custom: 'Обрати дні', time_suggested: 'Рекомендований час', save_changes: 'Зберегти зміни' },
    resumen: { title: 'Підсумки дня', subtitle: 'Візуалізуйте свій прогрес та переглядайте річну статистику.', progress_general: 'Загальний прогрес на сьогодні', legend_completed: 'Виконано', legend_justified: 'З причиною', legend_pending: 'Очікує', legend_rest: 'Відпочинок', legend_missed: 'Пропущено', history_title: 'Річний календар активності', tooltip_info: 'Наведіть курсор або натисніть на жовтий день, щоб побачити причину.', frequency: 'Частота' },
    analizar: { title: 'Аналіз звичок', subtitle: 'Слідкуйте за вашими серіями та загальною стабільністю.', current_streak: 'Поточна серія', max_streak: 'Максимальна серія', consistency: 'Стабільність', commitment: 'Всього днів за розкладом', times: 'разів', days_count: 'дн.', creation: 'Дата створення', select: 'Оберіть звичку', comparison: 'Порівняння стабільності (%)' },
    ajustes: { title: 'Налаштування', subtitle: 'Налаштуйте мову, профілі та сесію.', language: 'Мова додатка', profiles: 'Профілі звичок', active_profile: 'Активний профіль', new_profile: 'Новий профіль', create_profile: 'Створити профіль', cannot_delete_main: 'Основний профіль видалити не можна.', profiles_desc: 'Створюйте профілі для розділення звичок (напр., Спорт, Відпустка). У кожному профілі свої звички.', demo_alert: 'Запущено в демо-режимі', logout: 'Вийти' },
    importar: { title: 'Імпорт рутин', subtitle: 'Додавайте популярні шаблони або рутини спільноти.', default_routines: 'Стандартні шаблони', community_routines: 'Рутини спільноти', share_routine: 'Поділитися рутиною зі спільнотою', share_desc: 'Поділіться списком звичок із цього профілю як шаблоном для інших.', share_btn: 'Опублікувати рутину профілю', import_btn: 'Імпортувати', import_modal_title: 'Імпорт рутини', import_modal_desc: 'Оберіть: імпортувати в поточний профіль чи створити новий.', target_profile: 'Профіль призначення', current_profile: 'Поточний профіль ({name})', new_profile_option: 'Створити новий профіль', new_profile_name: 'Ім\'я нового профілю', share_success: 'Рутину успішно опубліковано!', import_success: 'Рутину успішно імпортовано!' }
  }
};
